export const TIMELINE = [
  {
    day: "Day 1",
    date: "July 24, 2026",
    title: "The Assembly",
    description: "The gates open. Hardware exhibits, robotics qualifiers, and the first wave of ceremonies commence.",
    events: [
      { time: "08:00 AM → 10:30 AM", title: "Check-in", category: "milestone" },
      { time: "10:00 AM → 11:00 AM", title: "Opening Ceremony", category: "main" },
      { time: "11:00 AM → 06:00 PM", title: "Robotic Games (Qualifiers)", category: "competition" },
      { time: "11:00 AM → 06:00 PM", title: "Hardware Project Exhibition", category: "exhibition" },
      { time: "01:00 PM → 04:00 PM", title: "Lunch", category: "break" },
      { time: "02:00 PM → 05:00 PM", title: "Indoor Games & Mini Events", category: "activity",
        subEvents: [
          "Table Tennis",
          "Chess",
          "Carrom",
          "Quiz",
          "Reels Making",
          "Canvas Designing",
          "Photography",
        ]
      },
      { time: "02:00 PM → July 26, 3:00 PM", title: "Creative Events", category: "activity", description: "Spans all three days" },
      { time: "02:30 PM → 05:30 PM", title: "Model Evaluations", category: "judging" },
      { time: "05:00 PM → 06:15 PM", title: "Exhibition Certifications Ceremony", category: "main" },
      { time: "05:00 PM → 06:30 PM", title: "Vote of Thanks", category: "main" },
      { time: "06:00 PM → 07:15 PM", title: "Wrap Day 1", category: "milestone" },
    ],
  },
  {
    day: "Day 2",
    date: "July 25, 2026",
    title: "The Conjuring Begins",
    description: "The 58-hour hackathon officially starts. Workshops, mentorship rounds, and midnight CTFs dominate the schedule.",
    events: [
      { time: "06:00 AM → 09:00 AM", title: "Day 2 Starts", category: "milestone" },
      { time: "07:00 AM → 09:00 AM", title: "Venue Setup", category: "logistics" },
      { time: "08:00 AM → 10:00 AM", title: "Check-ins", category: "milestone" },
      { time: "10:00 AM → 11:00 AM", title: "Opening Ceremony", category: "main" },
      { time: "11:00 AM → July 26, 06:00 PM", title: "Hacking Starts!", category: "milestone", important: true },
      { time: "12:00 PM → 07:15 PM", title: "Gaming Tournament (Parallel Event)", category: "activity" },
      { time: "12:00 PM → 01:00 PM", title: "Workshop 1", category: "workshop" },
      { time: "12:30 PM → 01:00 PM", title: "Workshop 2", category: "workshop" },
      { time: "01:00 PM → 02:00 PM", title: "Lunch", category: "break" },
      { time: "01:30 PM → 07:00 PM", title: "Robotics (Finals)", category: "competition",
        subEvents: [
          "Line Follower (1:30 PM - 4:30 PM)",
          "Robo Soccer (1:30 PM - 4:30 PM)",
          "Robo Race (1:30 PM - 4:30 PM)",
          "Robo Sumo (1:30 PM - 4:30 PM)",
        ]
      },
      { time: "03:00 PM → 03:30 PM", title: "Workshop 3", category: "workshop" },
      { time: "03:30 PM → 04:00 PM", title: "Workshop 4", category: "workshop" },
      { time: "05:00 PM → 07:00 PM", title: "Mentorship Round", category: "mentorship" },
      { time: "07:45 PM → 10:45 PM", title: "CTF 1", category: "competition" },
      { time: "08:45 PM → 11:30 PM", title: "Dinner", category: "break" },
      { time: "10:00 PM → July 26, 01:00 AM", title: "Judging Phase 1", category: "judging" },
    ],
  },
  {
    day: "Day 3",
    date: "July 26, 2026",
    title: "The Final Evaluation",
    description: "The dust settles. Submissions, final judging, and the closing ceremony where victors are crowned.",
    events: [
      { time: "02:00 AM → 05:00 AM", title: "CTF 2", category: "competition" },
      { time: "08:00 AM → 10:00 AM", title: "Breakfast", category: "break" },
      { time: "08:30 AM → 11:00 AM", title: "CTF 3", category: "competition" },
      { time: "09:45 AM → 12:00 PM", title: "Project Submission", category: "milestone", important: true },
      { time: "12:00 PM → 01:00 PM", title: "Lunch", category: "break" },
      { time: "01:00 PM → 04:00 PM", title: "Competitive Programming", category: "competition" },
      { time: "01:30 PM → 04:30 PM", title: "Final Judging", category: "judging", important: true },
      { time: "03:15 PM → 04:45 PM", title: "Evaluation", category: "judging" },
      { time: "04:15 PM → 05:00 PM", title: "Closing Ceremony", category: "main", important: true },
      { time: "05:00 PM → 08:00 PM", title: "Wrap up", category: "milestone" },
    ],
  },
];
